//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDKI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDescription
    {
        public tblDescription()
        {
            this.tblHistoricalFinancialStatements = new HashSet<tblHistoricalFinancialStatement>();
        }
    
        public long DescriptionID { get; set; }
        public string DescriptionName { get; set; }
    
        public virtual ICollection<tblHistoricalFinancialStatement> tblHistoricalFinancialStatements { get; set; }
    }
}
