//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDKI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistoricalFinancialStatement
    {
        public long DescriptionID { get; set; }
        public long GroupID { get; set; }
        public long TypeID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> SummationGrouping { get; set; }
    
        public virtual tblDescription tblDescription { get; set; }
        public virtual tblGroup tblGroup { get; set; }
    }
}
