//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDKI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMainAssumption
    {
        public long MADescriptionID { get; set; }
        public long MAGroupID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Value { get; set; }
    }
}
