//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDKI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOAType
    {
        public long OATypeID { get; set; }
        public string OATypeName { get; set; }
    }
}
