//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDKI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAuditedFS_SA_Summation
    {
        public string DescriptionName { get; set; }
        public long DescriptionID { get; set; }
        public string GroupName { get; set; }
        public string TypeName { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Value { get; set; }
        public Nullable<decimal> Summation { get; set; }
        public long GroupId { get; set; }
    }
}
